# Generated by Django 6.1 on 2026-08-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='review',
        ),
    ]
